spring:
  application:
    name: producer-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        orderChannel:
          destination: order

server:
  port: 8080